# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
apt-get update

echo "Download windows files"

wget -O w7x64.img https://bit.ly/akuhnetw7X64

echo "Download ngrok"

wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > /dev/null 2>&1

unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1

read -p "Ctrl + V Authtoken: " CRP 

./ngrok authtoken $CRP 

nohup ./ngrok tcp 3388 &>/dev/null &

echo Downloading File From akuh.net

apt-get install qemu-system-x86 -y

echo "Wait"

echo "Starting Windows"

qemu-system-x86_64 -hda w7x64.img -m 4G -smp cores=4 -net user,hostfwd=tcp::3388-:3389 -net nic -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 -vga vmware -nographic &>/dev/null &

clear

echo RDP Address:

curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'

echo "===================================="

echo "Username: akuh"

echo "Password: Akuh.Net"

echo "===================================="

echo "===================================="

echo "Keep supporting akuh.net, thank you"

echo "You Got Free RDP now"

echo "Wait 2 minute to finish bot"

echo "You can close this tab"

echo "RDP runs for 50 hours"

echo "===================================="

sleep 432000
